package dental_management_system;

import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bushra
 */
public class InsertAppointmentData extends javax.swing.JFrame
{
    User user;
      
    public InsertAppointmentData() 
    {
        initComponents();
    }
     public InsertAppointmentData(User user) 
     {
         initComponents();
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
        this.user = user;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbID = new javax.swing.JTextField();
        tbName = new javax.swing.JTextField();
        tbdate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_treatment = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 829, 493));
        setPreferredSize(new java.awt.Dimension(829, 493));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(tbID);
        tbID.setBounds(370, 80, 330, 50);

        tbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNameActionPerformed(evt);
            }
        });
        getContentPane().add(tbName);
        tbName.setBounds(370, 140, 330, 40);

        tbdate.setText("yyyy-MM-dd HH:mm:ss");
        getContentPane().add(tbdate);
        tbdate.setBounds(370, 190, 330, 40);

        jLabel1.setText("Patient ID ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 90, 90, 30);

        jLabel2.setText(" Patient Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 140, 120, 40);

        jLabel3.setText("   Date & Time");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 190, 120, 40);

        jTextField_treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_treatmentActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_treatment);
        jTextField_treatment.setBounds(370, 240, 340, 50);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("   Treatment");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 250, 110, 40);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 300, 110, 100);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel4.setText("            NEW APPOINTMENT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 10, 420, 50);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 180, 190);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 830, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNameActionPerformed

    private void jTextField_treatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_treatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_treatmentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        AppointmentList AList = new AppointmentList();
        AList.PateintID = Integer.parseInt(tbID.getText());
        
        //formatting required date and time as per required yyyy-MM-dd HH:mm:ss DATETIME data type in MySQL below
        java.text.SimpleDateFormat format = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        
        //first creating javadate variable of Date datatype
        java.util.Date javadate=null;
        try 
        {
            //converting date we have in string in the textfield to javadate variable
            javadate = format.parse(tbdate.getText());
        } 
        catch (ParseException ex) 
        {
            Logger.getLogger(InsertPatientData.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //now creating sqldatetime variable of Timestamp datatype which works with DATETIME datatype of MySQL.
        //sqldatetime variables takes its date and time from javadate variable above
        java.sql.Timestamp sqldatetime = new java.sql.Timestamp(javadate.getTime());

        //finally setting date and time in AList (AList.date) from sqldatetime variable
        AList.date = sqldatetime;

        AList.PatientName = tbName.getText();
        AList.Treatment = jTextField_treatment.getText();
        

        Receptionist recept = new  Receptionist(user.userName,user.password,user.userType);

        recept.InsertAppointmentData(AList);

        JOptionPane.showMessageDialog(rootPane, "Record added successfully.");

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertAppointmentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertAppointmentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertAppointmentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertAppointmentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertAppointmentData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField_treatment;
    private javax.swing.JTextField tbID;
    private javax.swing.JTextField tbName;
    private javax.swing.JTextField tbdate;
    // End of variables declaration//GEN-END:variables
}
