package dental_management_system;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author bushra
 */
public class InsertPatientData extends javax.swing.JFrame {

      User user;
    public InsertPatientData() 
    {
        initComponents();
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
    }
    
     public InsertPatientData(User user) 
     {
         initComponents();
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
        
        this.user = user;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbID = new javax.swing.JTextField();
        tbName = new javax.swing.JTextField();
        tbPhone = new javax.swing.JTextField();
        jTextField_PDH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAddNewRecord = new javax.swing.JButton();
        jTextField_PMH = new javax.swing.JTextField();
        jTextField_PSH = new javax.swing.JTextField();
        jTextField_DHx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 844, 503));
        setPreferredSize(new java.awt.Dimension(844, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        tbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbIDActionPerformed(evt);
            }
        });
        getContentPane().add(tbID);
        tbID.setBounds(410, 60, 360, 40);

        tbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNameActionPerformed(evt);
            }
        });
        getContentPane().add(tbName);
        tbName.setBounds(410, 100, 360, 40);
        getContentPane().add(tbPhone);
        tbPhone.setBounds(410, 140, 360, 40);

        jTextField_PDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PDHActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_PDH);
        jTextField_PDH.setBounds(410, 180, 360, 50);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 60, 140, 40);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 110, 87, 22);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 150, 70, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PDH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 190, 80, 40);

        btnAddNewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dental_management_system/images/approve.png"))); // NOI18N
        btnAddNewRecord.setBorderPainted(false);
        btnAddNewRecord.setContentAreaFilled(false);
        btnAddNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddNewRecord);
        btnAddNewRecord.setBounds(550, 380, 90, 100);

        jTextField_PMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PMHActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_PMH);
        jTextField_PMH.setBounds(410, 230, 360, 50);

        jTextField_PSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PSHActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_PSH);
        jTextField_PSH.setBounds(410, 280, 360, 50);
        getContentPane().add(jTextField_DHx);
        jTextField_DHx.setBounds(410, 330, 360, 50);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PMH");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 230, 60, 40);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" PSH");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 280, 60, 40);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DHx");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 320, 50, 40);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("            History Of Patient ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 10, 510, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dental_management_system/images/appbackground copy.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 840, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNameActionPerformed

    private void btnAddNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewRecordActionPerformed

        Patient patient = new Patient();
        patient.ID = Integer.parseInt(tbID.getText());
        patient.name = tbName.getText();
        patient.phoneNumber = Integer.parseInt(tbPhone.getText());
        patient.pastDentalhistory = jTextField_PDH.getText();
        patient.pastMedicalhistory = jTextField_PMH.getText();
        patient.pastSurgicalhistory = jTextField_PSH.getText();
        patient.pastDrughistory = jTextField_DHx.getText();

        Receptionist recept = new  Receptionist(user.userName,user.password,user.userType);

        recept.InsertPatientData(patient);

        JOptionPane.showMessageDialog(rootPane, "Record added successfully.");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddNewRecordActionPerformed

    private void jTextField_PDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PDHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PDHActionPerformed

    private void jTextField_PMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PMHActionPerformed

    private void jTextField_PSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PSHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PSHActionPerformed

    private void tbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertPatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertPatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertPatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertPatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertPatientData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_DHx;
    private javax.swing.JTextField jTextField_PDH;
    private javax.swing.JTextField jTextField_PMH;
    private javax.swing.JTextField jTextField_PSH;
    private javax.swing.JTextField tbID;
    private javax.swing.JTextField tbName;
    private javax.swing.JTextField tbPhone;
    // End of variables declaration//GEN-END:variables
}
