package dental_management_system;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bushra
 */
public class ViewExpensesRecord extends javax.swing.JFrame 
{

    User user;
    ResultSet rs; 
    public ViewExpensesRecord()
    {
        initComponents();
    }
     public ViewExpensesRecord(User user)
    {
                initComponents();
                this.setLocationRelativeTo(null); // for centering form on screen
                this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
                this.user =user;
                if("Admin".equals(user.userType))
        {
           Admin admin = new Admin(user.userName,user.password,user.userType);
          
           
            
            
                try
                {
                    
                rs = admin.ShowAllExpensesRecord();

                while(jTable1_expensesrecord.getRowCount() > 0) 
                {
                    ((DefaultTableModel) jTable1_expensesrecord.getModel()).removeRow(0);

                }


                int columns = rs.getMetaData().getColumnCount();


                while(rs.next())
                {  

                    Object[] row = new Object[columns];
                    for (int i = 1; i <= columns; i++)
                    {  
                        row[i - 1] = rs.getObject(i);
                    }
                    ((DefaultTableModel) jTable1_expensesrecord.getModel()).insertRow(rs.getRow()-1,row);
                }

                }
                catch (Exception e)
                {

                }  
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_expensesrecord = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1_search = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_refresh = new javax.swing.JMenu();
        jMenuItem6_refresh = new javax.swing.JMenuItem();
        jMenu2_addnewrecord = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 780, 520));
        setPreferredSize(new java.awt.Dimension(780, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1_expensesrecord.setBackground(new java.awt.Color(0, 102, 255));
        jTable1_expensesrecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Month", "Payments", "Electricity Bill", "Water Bills", "Maintenance Expense"
            }
        ));
        jTable1_expensesrecord.setBounds(new java.awt.Rectangle(0, 23, 900, 800));
        jTable1_expensesrecord.setMinimumSize(new java.awt.Dimension(900, 800));
        jTable1_expensesrecord.setPreferredSize(new java.awt.Dimension(900, 800));
        jScrollPane1.setViewportView(jTable1_expensesrecord);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 110, 780, 280);

        jTextField1.setBackground(new java.awt.Color(0, 153, 255));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 20, 560, 60);

        jButton1_search.setText("Search");
        jButton1_search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_search);
        jButton1_search.setBounds(610, 20, 130, 60);

        jMenu1_refresh.setText("File");

        jMenuItem6_refresh.setText("Refresh");
        jMenuItem6_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6_refreshActionPerformed(evt);
            }
        });
        jMenu1_refresh.add(jMenuItem6_refresh);

        jMenuBar1.add(jMenu1_refresh);

        jMenu2_addnewrecord.setText("Functions");

        jMenuItem1.setText("Add new record");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2_addnewrecord.add(jMenuItem1);

        jMenuBar1.add(jMenu2_addnewrecord);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6_refreshActionPerformed
        jTextField1.setText("");
         this.jButton1_searchActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem6_refreshActionPerformed

    private void jButton1_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_searchActionPerformed
       
         Admin admin = new Admin(user.userName,user.password,user.userType);
         rs = admin.SearchExpensesData(jTextField1.getText());
         
         try
        {

        
        while(jTable1_expensesrecord.getRowCount() > 0) 
        {
            ((DefaultTableModel) jTable1_expensesrecord.getModel()).removeRow(0);
        }
        int columns = rs.getMetaData().getColumnCount();
        while(rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                row[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel) jTable1_expensesrecord.getModel()).insertRow(rs.getRow()-1,row);
        }
        
        
        }
        catch (Exception e)
        {
        
        }
    }//GEN-LAST:event_jButton1_searchActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new InsertExpensesRecord(user).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewExpensesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewExpensesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewExpensesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewExpensesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewExpensesRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_search;
    private javax.swing.JMenu jMenu1_refresh;
    private javax.swing.JMenu jMenu2_addnewrecord;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6_refresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_expensesrecord;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
