package dental_management_system;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author bushra
 */
public class ViewAppointmentList extends javax.swing.JFrame 
{
    User user;
    ResultSet rs; 
  
    public ViewAppointmentList()
    {
        initComponents();
    }
    public ViewAppointmentList(User user)
    {
        initComponents();
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
        
        this.user = user;
        
        
        if("Receptionist".equals(user.userType))
        {
            Receptionist recept = new Receptionist(user.userName,user.password,user.userType);
            
            
            
            
            
            try
                {

                rs = recept.ShowAllAppointments();
                    
                while(jTable1_appointment.getRowCount() > 0) 
                {
                    ((DefaultTableModel) jTable1_appointment.getModel()).removeRow(0);

                }


                int columns = rs.getMetaData().getColumnCount();


                while(rs.next())
                {  

                    Object[] row = new Object[columns];
                    for (int i = 1; i <= columns; i++)
                    {  
                        row[i - 1] = rs.getObject(i);
                    }
                    ((DefaultTableModel) jTable1_appointment.getModel()).insertRow(rs.getRow()-1,row);
                }

            }
        catch (Exception e)
        {
                
        }  
            
        }
        
        
        if("Doctor".equals(user.userType))
        {
            Doctor doc = new Doctor(user.userName,user.password,user.userType);
          
           jMenu1_add.disable(); //none of the below menuitem actions will show
            
            
                try
                {
                    
                rs = doc.ShowAllPatientsData();

                while(jTable1_appointment.getRowCount() > 0) 
                {
                    ((DefaultTableModel) jTable1_appointment.getModel()).removeRow(0);

                }


                int columns = rs.getMetaData().getColumnCount();


                while(rs.next())
                {  

                    Object[] row = new Object[columns];
                    for (int i = 1; i <= columns; i++)
                    {  
                        row[i - 1] = rs.getObject(i);
                    }
                    ((DefaultTableModel) jTable1_appointment.getModel()).insertRow(rs.getRow()-1,row);
                }

                }
                catch (Exception e)
                {

                }  
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_appointment = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_add = new javax.swing.JMenu();
        jMenuItem1_add = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 780, 540));
        setPreferredSize(new java.awt.Dimension(780, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1_appointment.setBackground(new java.awt.Color(51, 102, 255));
        jTable1_appointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Full Name", "Date & Time", "Treatment"
            }
        ));
        jTable1_appointment.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1_appointment.setBounds(new java.awt.Rectangle(0, 23, 900, 800));
        jTable1_appointment.setPreferredSize(new java.awt.Dimension(900, 800));
        jScrollPane1.setViewportView(jTable1_appointment);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 20, 920, 460);

        jMenu1_add.setText("File");

        jMenuItem1_add.setText("Add new appointment");
        jMenuItem1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_addActionPerformed(evt);
            }
        });
        jMenu1_add.add(jMenuItem1_add);

        jMenuBar1.add(jMenu1_add);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_addActionPerformed
     new InsertAppointmentData(user).setVisible(true);  
    }//GEN-LAST:event_jMenuItem1_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAppointmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAppointmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAppointmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAppointmentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAppointmentList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1_add;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_add;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_appointment;
    // End of variables declaration//GEN-END:variables
}
