package dental_management_system;

import java.sql.*;

/**
 *
 * @author bushra
 */
public class ViewMedicinesrecord extends javax.swing.JFrame {

    User user;
    ResultSet rs; 
   
    public ViewMedicinesrecord()
    {
        initComponents();
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
    }
    public ViewMedicinesrecord(User user)
    {
        initComponents();
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
        
        this.user = user;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1_medicines = new javax.swing.JButton();
        jButton2_equipments = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(0, 102, 255));
        jLabel3.setMaximumSize(new java.awt.Dimension(724, 471));
        jLabel3.setMinimumSize(new java.awt.Dimension(724, 471));
        jLabel3.setPreferredSize(new java.awt.Dimension(724, 471));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setPreferredSize(new java.awt.Dimension(724, 471));
        setResizable(false);
        setSize(new java.awt.Dimension(724, 471));
        getContentPane().setLayout(null);

        jButton1_medicines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dental_management_system/images/medicinerecordbtn copy.png"))); // NOI18N
        jButton1_medicines.setBorderPainted(false);
        jButton1_medicines.setContentAreaFilled(false);
        jButton1_medicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_medicinesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_medicines);
        jButton1_medicines.setBounds(110, 140, 250, 180);

        jButton2_equipments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dental_management_system/images/Blood_Pressure_Kit-512.png"))); // NOI18N
        jButton2_equipments.setBorderPainted(false);
        jButton2_equipments.setContentAreaFilled(false);
        jButton2_equipments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_equipmentsActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2_equipments);
        jButton2_equipments.setBounds(420, 80, 240, 260);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Medicines");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 360, 220, 50);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("     Equipments");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 360, 280, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dental_management_system/images/appbackground copy.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 720, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_medicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_medicinesActionPerformed
       new Record_Of_Medicines(user).setVisible(true);
    }//GEN-LAST:event_jButton1_medicinesActionPerformed

    private void jButton2_equipmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_equipmentsActionPerformed
        new Record_Of_Equipments(user).setVisible(true);
    }//GEN-LAST:event_jButton2_equipmentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMedicinesrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMedicinesrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMedicinesrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMedicinesrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMedicinesrecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_medicines;
    private javax.swing.JButton jButton2_equipments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
